apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"60000":{"name": "hello-world-2-neg"}}}'
spec:
  selector:
    greeting: hello
    version: two
  ports:
  - protocol: TCP
    port: 60000 
    targetPort: 50000 
  type: NodePort
